# Generated by Django 5.1.1 on 2024-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentanswers_assessmentquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentlink',
            name='link',
        ),
        migrations.AddField(
            model_name='assessmentlink',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
