# Generated by Django 5.1.1 on 2024-09-18 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_assessmentlink_link_assessmentlink_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCode',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_for', models.TextField(blank=True, null=True)),
                ('assessment_type', models.CharField(choices=[('ONE', 'ONE'), ('MANY', 'MANY')], default='ONE', max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_link', to='assessment.assessment')),
            ],
            options={
                'db_table': 'assessment_code',
            },
        ),
        migrations.DeleteModel(
            name='AssessmentLink',
        ),
    ]
