# Generated by Django 5.1.1 on 2024-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentcode_delete_assessmentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'email_table',
            },
        ),
        migrations.RemoveField(
            model_name='assessmentcode',
            name='access_for',
        ),
        migrations.AddField(
            model_name='assessmentcode',
            name='access_for',
            field=models.ManyToManyField(blank=True, to='assessment.email'),
        ),
    ]
