# Generated by Django 5.1.1 on 2024-09-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_email_remove_assessmentcode_access_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentskills',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_skills', to='assessment.assessment'),
        ),
    ]
