# Generated by Django 5.1.1 on 2024-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_assessmentanswers_answer_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentanswers',
            name='answer_audio',
            field=models.FileField(blank=True, null=True, upload_to='answer_audio/'),
        ),
        migrations.AlterField(
            model_name='assessmentanswers',
            name='answer_video',
            field=models.FileField(blank=True, null=True, upload_to='answer_video/'),
        ),
        migrations.AlterField(
            model_name='assessmentquestions',
            name='question_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_audio/'),
        ),
    ]
