#!/bin/bash

set -o errexit
set -o nounset

celery -A saksatkara worker -l INFO --concurrency=10 -n worker1@%h
celery -A saksatkara worker -l INFO --concurrency=10 -n worker2@%h
celery -A saksatkara worker -l INFO --concurrency=10 -n worker3@%h