
'''

    Here we are adding message that should map with our response['message']

'''

class response_message:
    message = {
    'data_not_created' : 'Data Not Created',
    'data_not_found' : 'Data Not Found',
    'required_field' : 'Required Field',
    'update_failed' : 'Update Failed',
    'delete_failed' : 'Delete Failed',
    'request_failed' : 'Json Request Failed',
    'json_parse_error' : 'Json Parse Error',
    'serializer_error' : 'Serializer Error',
    'field_error' : 'Field Error',
    'server_error' : 'Something Went Wrong',
    'out_of_stock' : 'Product is Out of Stock',
    'success' : 'Success',
    'created' : 'Data Created',
    'otp-sent' : 'OTP Sent',
    'updated' : 'Data Updated',
    'deleted' : 'Deleted',
    'enabled' : 'Enabled',
    'paused' : 'Paused',
    'resumed' : 'Resumed',
    'failed' : 'Failed',
    'server_error' : 'Something Went Wrong',
    'value_error' : 'Invalid Request',
    'key_error' : 'Key Not Found',
    'service_request_timeout' : 'Request Time Out',
    'access_forbidden_error' : 'Access Is Forbidden',
    'service_unavailable' : 'Server Not Ready To Handle',
    'attribute_error' : 'Attribute Not Found',
    'password-incorrect' : 'Current Password is Incorrect',
    'method_not_allowed' : 'Method is not allowed',
    'otp_already_sent' : 'Otp is already sent',
    'limit_exceeded' : 'Your limit to get OTP exceeded please contact developer',
    'audio_not_matched' : 'User Audio is not Matching',
    'invalid_access_key' : 'Invalid Access Key',
    'verification_failed' : 'OTP verification failed, please enter correct OTP',
    'audio_failed' : 'Audio quality is not upto the mark please rerecord your audio',
    'permission_denied':'permission denied',
    'key_limit_exceeded' : 'Your limit has been exceeded for this key please contact developer',
    'user_already_exists' : 'User with this email id already exists',
    'slot_booked' : 'Success! Your slot has been booked, you will get notified via mail.',
    'slot_not_found' : 'Slot is not available.',
    'user_not_found' : 'User not found.',
    'slot_already_got_booked' : 'This Slot is already got booked for someone else, Please choose a new slot.',
    'refund_initiation_failed' : 'Refund Initiation is failed.',
    'refund_initiated' : 'Refund Initiated Successfully.',
    'payment_failed' : 'Payment Failed!',
    'booking_time_expired' : 'Your Booking time is expired.',
    'already_booked' : 'Your slot is already booked.',
    'slot_full' : 'Sorry! This slot is full, Please choose a different slot.',
}